let upstream =
    -- https://github.com/mlabs-haskell/purescript-cardano-package-set
      https://raw.githubusercontent.com/mlabs-haskell/purescript-cardano-package-set/v4.0.1/packages.dhall
        sha256:738a4057532f0dc140978b02964432d281011514e7ab9482053adaef4e4e7027

let additions =
      { cardano-transaction-lib =
        { dependencies =
         [ "aeson"
          , "aff"
          , "aff-promise"
          , "aff-retry"
          , "affjax"
          , "ansi"
          , "argonaut"
          , "argonaut-codecs"
          , "arrays"
          , "avar"
          , "bifunctors"
          , "bytearrays"
          , "cardano-blockfrost-provider"
          , "cardano-data-lite"
          , "cardano-hd-wallet"
          , "cardano-key-wallet"
          , "cardano-kupmios-provider"
          , "cardano-message-signing"
          , "cardano-ogmios-mempool"
          , "cardano-plutus-data-schema"
          , "cardano-provider"
          , "cardano-transaction-balancer"
          , "cardano-transaction-builder"
          , "cardano-types"
          , "checked-exceptions"
          , "cip30"
          , "cip30-mock"
          , "cip30-typesafe"
          , "cip95"
          , "cip95-typesafe"
          , "console"
          , "control"
          , "crypto"
          , "datetime"
          , "debug"
          , "effect"
          , "either"
          , "enums"
          , "exceptions"
          , "foldable-traversable"
          , "foreign"
          , "foreign-object"
          , "functions"
          , "http-methods"
          , "identity"
          , "integers"
          , "js-bigints"
          , "js-date"
          , "lattice"
          , "lists"
          , "literals"
          , "maybe"
          , "monad-logger"
          , "mote"
          , "mote-testplan"
          , "newtype"
          , "noble-secp256k1"
          , "node-buffer"
          , "node-child-process"
          , "node-fs"
          , "node-fs-aff"
          , "node-path"
          , "node-process"
          , "node-readline"
          , "node-streams"
          , "node-streams-aff"
          , "nonempty"
          , "now"
          , "nullable"
          , "numbers"
          , "optparse"
          , "ordered-collections"
          , "orders"
          , "parallel"
          , "parsing"
          , "partial"
          , "plutus-types"
          , "posix-types"
          , "prelude"
          , "profunctor"
          , "profunctor-lenses"
          , "quickcheck"
          , "quickcheck-combinators"
          , "random"
          , "record"
          , "refs"
          , "safe-coerce"
          , "safely"
          , "spec"
          , "spec-quickcheck"
          , "strings"
          , "stringutils"
          , "tailrec"
          , "toppokki"
          , "transformers"
          , "tuples"
          , "typelevel-prelude"
          , "uint"
          , "unfoldable"
          , "unsafe-coerce"
          , "uplc-apply-args"
          , "variant"
          , "web-html"
          , "web-storage"
          ]
        , repo = "https://github.com/Plutonomicon/cardano-transaction-lib.git"
        , version = "2f7751724f703f4c480df3d50204020932f64b83"
        }
      , codec-aeson =
        { dependencies =
          [ "aeson"
          , "argonaut-codecs"
          , "argonaut-core"
          , "arrays"
          , "bifunctors"
          , "codec"
          , "console"
          , "control"
          , "effect"
          , "either"
          , "exceptions"
          , "foldable-traversable"
          , "foreign-object"
          , "gen"
          , "integers"
          , "lists"
          , "maybe"
          , "newtype"
          , "ordered-collections"
          , "partial"
          , "prelude"
          , "profunctor"
          , "quickcheck"
          , "record"
          , "safe-coerce"
          , "strings"
          , "transformers"
          , "tuples"
          , "type-equality"
          , "typelevel-prelude"
          , "unsafe-coerce"
          , "variant"
          ]
        , repo = "https://github.com/errfrom/purescript-codec-argonaut.git"
        , version = "59996776e733a1e0f1daf085f153b2cca8527907"
        }
      , errors =
        { dependencies =
          [ "control"
          , "effect"
          , "either"
          , "identity"
          , "maybe"
          , "newtype"
          , "prelude"
          , "test-unit"
          , "transformers"
          ]
        , repo = "https://github.com/passy/purescript-errors.git"
        , version = "670485beb1e026f77d52ca58ce10c145d96c11ba"
        }
      , hydra-sdk =
        { dependencies =
          [ "aeson"
          , "aff"
          , "affjax"
          , "affjax-node"
          , "argonaut"
          , "arrays"
          , "avar"
          , "bifunctors"
          , "bytearrays"
          , "cardano-types"
          , "codec-aeson"
          , "control"
          , "datetime"
          , "effect"
          , "either"
          , "errors"
          , "exceptions"
          , "foldable-traversable"
          , "foreign-object"
          , "formatters"
          , "http-methods"
          , "integers"
          , "js-date"
          , "maybe"
          , "monad-logger"
          , "mote"
          , "mote-testplan"
          , "newtype"
          , "node-buffer"
          , "node-child-process"
          , "node-fs"
          , "node-path"
          , "node-process"
          , "node-streams"
          , "optparse"
          , "ordered-collections"
          , "parsing"
          , "partial"
          , "plutus-types"
          , "posix-types"
          , "prelude"
          , "profunctor"
          , "quickcheck"
          , "record"
          , "record-extra"
          , "safely"
          , "spec"
          , "strings"
          , "tailrec"
          , "transformers"
          , "tuples"
          , "uint"
          , "uri"
          , "uuid"
          ]
        , repo = "https://github.com/mlabs-haskell/purescript-hydra-sdk"
        , version = "18b8390370e1f4fd39a826cbce81dcedf3dd0992"
        }
      }

in (upstream // additions)
