{ name = "cardano-racers-offchain"
, dependencies =
  [ "aeson"
  , "aff"
  , "aff-promise"
  , "affjax"
  , "arraybuffer-types"
  , "arrays"
  , "bifunctors"
  , "bigints"
  , "bytearrays"
  , "cardano-data-lite"
  , "cardano-key-wallet"
  , "cardano-plutus-data-schema"
  , "cardano-provider"
  , "cardano-transaction-lib"
  , "cardano-types"
  , "codec-aeson"
  , "console"
  , "control"
  , "datetime"
  , "effect"
  , "either"
  , "encoding"
  , "errors"
  , "exceptions"
  , "foldable-traversable"
  , "foreign"
  , "foreign-object"
  , "functions"
  , "http-methods"
  , "hydra-sdk"
  , "integers"
  , "js-bigints"
  , "lcg"
  , "lists"
  , "literals"
  , "maybe"
  , "mote"
  , "newtype"
  , "numbers"
  , "ordered-collections"
  , "partial"
  , "plutus-types"
  , "posix-types"
  , "prelude"
  , "profunctor"
  , "quickcheck"
  , "record"
  , "refs"
  , "spec"
  , "strings"
  , "transformers"
  , "tuples"
  , "typelevel-prelude"
  , "uint"
  , "unsafe-coerce"
  , "uplc-apply-args"
  , "web-html"
  , "web-storage"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "exe/**/*.purs", "test/**/*.purs" ]
}
