let upstream =
    -- https://github.com/mlabs-haskell/purescript-cardano-package-set
      https://raw.githubusercontent.com/mlabs-haskell/purescript-cardano-package-set/v4.0.0/packages.dhall
        sha256:3c2ed3da5ea24434d71c93748594cddcd9feedeadf170e0687ffd47916de1f97

let additions =
      { aeson =
        { dependencies =
          [ "aff"
          , "argonaut"
          , "argonaut-codecs"
          , "argonaut-core"
          , "arrays"
          , "bifunctors"
          , "const"
          , "control"
          , "effect"
          , "either"
          , "exceptions"
          , "foldable-traversable"
          , "foreign-object"
          , "integers"
          , "js-bigints"
          , "lists"
          , "maybe"
          , "mote"
          , "numbers"
          , "ordered-collections"
          , "partial"
          , "prelude"
          , "quickcheck"
          , "record"
          , "spec"
          , "strings"
          , "tuples"
          , "typelevel"
          , "typelevel-prelude"
          , "uint"
          , "untagged-union"
          ]
        , repo = "https://github.com/mlabs-haskell/purescript-aeson.git"
        , version = "e7bfc24a941e1d73de88de3f4a034e1da33cc8ae"
        }
      , cardano-data-lite =
        { dependencies =
          [ "aeson"
          , "aff"
          , "argonaut"
          , "bifunctors"
          , "bytearrays"
          , "effect"
          , "either"
          , "enums"
          , "maybe"
          , "newtype"
          , "nullable"
          , "ordered-collections"
          , "partial"
          , "prelude"
          , "profunctor"
          , "spec"
          , "transformers"
          , "tuples"
          , "unsafe-coerce"
          ]
        , repo = "https://github.com/mlabs-haskell/purescript-cardano-data-lite"
        , version = "44a08930844221afc4ef750104940f81a75b996e"
        } 
      , cardano-transaction-lib =
        { dependencies =
          [ "aeson"
          , "aff"
          , "aff-promise"
          , "aff-retry"
          , "affjax"
          , "ansi"
          , "argonaut"
          , "argonaut-codecs"
          , "arrays"
          , "avar"
          , "bifunctors"
          , "bytearrays"
          , "cardano-blockfrost-provider"
          , "cardano-data-lite"
          , "cardano-hd-wallet"
          , "cardano-key-wallet"
          , "cardano-kupmios-provider"
          , "cardano-message-signing"
          , "cardano-ogmios-mempool"
          , "cardano-plutus-data-schema"
          , "cardano-provider"
          , "cardano-transaction-balancer"
          , "cardano-transaction-builder"
          , "cardano-types"
          , "checked-exceptions"
          , "cip30"
          , "cip30-mock"
          , "cip30-typesafe"
          , "cip95"
          , "cip95-typesafe"
          , "console"
          , "control"
          , "crypto"
          , "datetime"
          , "debug"
          , "effect"
          , "either"
          , "enums"
          , "exceptions"
          , "foldable-traversable"
          , "foreign"
          , "foreign-object"
          , "functions"
          , "http-methods"
          , "identity"
          , "integers"
          , "js-bigints"
          , "js-date"
          , "lattice"
          , "lists"
          , "literals"
          , "maybe"
          , "monad-logger"
          , "mote"
          , "mote-testplan"
          , "newtype"
          , "noble-secp256k1"
          , "node-buffer"
          , "node-child-process"
          , "node-fs"
          , "node-fs-aff"
          , "node-path"
          , "node-process"
          , "node-readline"
          , "node-streams"
          , "node-streams-aff"
          , "nonempty"
          , "now"
          , "nullable"
          , "numbers"
          , "optparse"
          , "ordered-collections"
          , "orders"
          , "parallel"
          , "parsing"
          , "partial"
          , "plutus-types"
          , "posix-types"
          , "prelude"
          , "profunctor"
          , "profunctor-lenses"
          , "quickcheck"
          , "quickcheck-combinators"
          , "random"
          , "record"
          , "refs"
          , "safe-coerce"
          , "safely"
          , "spec"
          , "spec-quickcheck"
          , "strings"
          , "stringutils"
          , "tailrec"
          , "toppokki"
          , "transformers"
          , "tuples"
          , "typelevel-prelude"
          , "uint"
          , "unfoldable"
          , "unsafe-coerce"
          , "uplc-apply-args"
          , "variant"
          , "web-html"
          , "web-storage"
          ]
        , repo = "https://github.com/Plutonomicon/cardano-transaction-lib.git"
        , version = "3c3c69be74e70211d05768659e254b4c733def84"
        }
      , codec-aeson =
        { dependencies =
          [ "aeson"
          , "argonaut-codecs"
          , "argonaut-core"
          , "arrays"
          , "bifunctors"
          , "codec"
          , "console"
          , "control"
          , "effect"
          , "either"
          , "exceptions"
          , "foldable-traversable"
          , "foreign-object"
          , "gen"
          , "integers"
          , "lists"
          , "maybe"
          , "newtype"
          , "ordered-collections"
          , "partial"
          , "prelude"
          , "profunctor"
          , "quickcheck"
          , "record"
          , "safe-coerce"
          , "strings"
          , "transformers"
          , "tuples"
          , "type-equality"
          , "typelevel-prelude"
          , "unsafe-coerce"
          , "variant"
          ]
        , repo = "https://github.com/errfrom/purescript-codec-argonaut.git"
        , version = "59996776e733a1e0f1daf085f153b2cca8527907"
        }
      , errors =
        { dependencies =
          [ "control"
          , "effect"
          , "either"
          , "identity"
          , "maybe"
          , "newtype"
          , "prelude"
          , "test-unit"
          , "transformers"
          ]
        , repo = "https://github.com/passy/purescript-errors.git"
        , version = "670485beb1e026f77d52ca58ce10c145d96c11ba"
        }
      , hydra-sdk =
        { dependencies =
          [ "aeson"
          , "aff"
          , "affjax"
          , "affjax-node"
          , "argonaut"
          , "arrays"
          , "avar"
          , "bifunctors"
          , "bytearrays"
          , "cardano-types"
          , "codec-aeson"
          , "control"
          , "datetime"
          , "effect"
          , "either"
          , "errors"
          , "exceptions"
          , "foldable-traversable"
          , "foreign-object"
          , "formatters"
          , "http-methods"
          , "integers"
          , "js-date"
          , "maybe"
          , "monad-logger"
          , "mote"
          , "mote-testplan"
          , "newtype"
          , "node-buffer"
          , "node-child-process"
          , "node-fs"
          , "node-path"
          , "node-process"
          , "node-streams"
          , "optparse"
          , "ordered-collections"
          , "parsing"
          , "partial"
          , "plutus-types"
          , "posix-types"
          , "prelude"
          , "profunctor"
          , "quickcheck"
          , "record"
          , "safely"
          , "spec"
          , "strings"
          , "tailrec"
          , "transformers"
          , "tuples"
          , "uint"
          , "uri"
          , "uuid"
          ]
        , repo = "https://github.com/mlabs-haskell/purescript-hydra-sdk"
        , version = "2059acaaf11b8bc45172bd68bc6140d385e90bf3"
        }
      }

in (upstream // additions)
