{ name = "cardano-racers-hydra"
, dependencies =
  [ "aeson"
  , "aff"
  , "aff-retry"
  , "arrays"
  , "avar"
  , "bifunctors"
  , "bytearrays"
  , "cardano-provider"
  , "cardano-racers-offchain"
  , "cardano-transaction-lib"
  , "cardano-types"
  , "codec-aeson"
  , "console"
  , "datetime"
  , "effect"
  , "either"
  , "errors"
  , "exceptions"
  , "foldable-traversable"
  , "httpure"
  , "hydra-sdk"
  , "identity"
  , "integers"
  , "js-bigints"
  , "js-timers"
  , "maybe"
  , "monad-logger"
  , "newtype"
  , "node-buffer"
  , "node-child-process"
  , "node-fs"
  , "node-fs-aff"
  , "node-path"
  , "node-process"
  , "node-streams"
  , "numbers"
  , "ordered-collections"
  , "parallel"
  , "partial"
  , "plutus-types"
  , "posix-types"
  , "prelude"
  , "profunctor"
  , "profunctor-lenses"
  , "record"
  , "refs"
  , "strings"
  , "tailrec"
  , "transformers"
  , "tuples"
  , "uint"
  , "uri"
  , "variant"
  ]
, packages = ./packages.dhall
, sources =
  [ "app/**/*.purs", "demo/**/*.purs", "src/**/*.purs", "test/**/*.purs" ]
}
